# Generated by Django 5.0.6 on 2024-06-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoshIsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boshish', models.CharField(max_length=70)),
                ('talablar', models.CharField(max_length=100)),
                ('ishxaqi', models.CharField(max_length=50)),
                ('stavka', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HududiyBolimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('manzil', models.CharField(max_length=50)),
            ],
        ),
    ]
