# Generated by Django 5.0.6 on 2024-06-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0002_boshish_qoshimchaishxaqi_alter_boshish_boshish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boshish',
            name='talablar',
            field=models.CharField(max_length=500),
        ),
    ]
