# Generated by Django 5.0.6 on 2024-06-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0003_alter_boshish_talablar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matbuotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='')),
                ('sarlavha', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('matn', models.CharField(max_length=1000)),
            ],
        ),
    ]
